### PR TITLE
Lingering update

### PR DESCRIPTION
**Pull request by Txus5012**
Lingering symptom had a few issues:
- Difficulty wasn't set in roll dialog.
- Using the difficulty keys made "Very Easy" and "Very Hard" not to work. Also, localized difficulties didn't work.
- This didn't work at all with localized symptoms.

### CODE REVIEW

**Comment by moo-man** [comment]
I'm not going to have property keys be in the localization JSON, so an alternative way of doing this will need to be found. If the symptoms are overridden with their localized values, you should be able to use `findKey` in the difficulty config object to get the difficulty property key.

**Comment by Txus5012** [comment]
I'm not sure if I'm understanding this well. I'm not localizing the difficulty keys. I just added some strings for the difficulty names without the modifier (e.g. "Easy" instead of "Easy (+40)" ).
Anyway, I see what you mean with findKey. I'll take a look at that.

**Comment by Txus5012** [comment]
Added difficultyNames to config and used it for finding the difficulty key.
Also added a line break in the message, I think it looks better.

**Comment by moo-man** [comment]
I was referring to this, which yeah looking at it now wasn't exactly keys, but I still think the localization JSON should strictly be for display. Anyway, it's looking better now. 

image

**Comment by Txus5012** [comment]
The lang file has the names of skills, talents and traits. This is the same.

**Comment by moo-man** [comment]
I've moved the PR to the master branch as I've merged `effect-refactor`

The conflict is only from `skipTargets` added to the test, so should be easy to resolve.

**Pull request merged**
