### PR TITLE
Styling improvements for Active Effect Sheet and Script Config

### PR DESCRIPTION
**Pull request by Forien**
## Active Effect Sheet
- Widened sheet by 30 pixels so that ProseMirror's controls are in single line
- added parchment background to match that of the RollTable (probably not the best looking, but easiest approach, because it doesn't involve the need to change prosemirror's font colors etc)  

image

## Active Effect's Script Config app
- Modified Script Config so script textarea fills the available area (using flex box), and it's working well with dynamically changing form based on trigger)
- Made config a little bit bigger by default
- Set font to 12px monospace. Personally I think it looks a little better 
  - That said I think there are google fonts that would work a lot better/have a cleaner look, for example [Source Code Pro](https://fonts.google.com/specimen/Source+Code+Pro?preview.text=let%20wounds%20%3D%20this.actor.status.wounds%20if%20(wounds.value%20%3D%3D%200)%20%20%20return%20ui.notifications.error(%22No%20effect%20at%200%20Wounds%22)%20%20ui.notifications.notify(%60Healed%20$%7Bthis.actor.characteristics.t.bonus%7D%20Wounds%60)%20this.actor.modifyWounds(this.actor.characteristics.t.bonus)&classification=Monospace), [Roboto Mono](https://fonts.google.com/specimen/Roboto+Mono?preview.text=let%20wounds%20%3D%20this.actor.status.wounds%20if%20(wounds.value%20%3D%3D%200)%20%20%20%0A%20%20%20%20return%20ui.notifications.error(%22No%20effect%20at%200%20Wounds%22)%20%20%0A%0Aui.notifications.notify(%60Healed%20$%7Bthis.actor.characteristics.t.bonus%7D%20Wounds%60)%20%0Athis.actor.modifyWounds(this.actor.characteristics.t.bonus)&classification=Monospace) or [Inconsolata](https://fonts.google.com/specimen/Inconsolata?preview.text=let%20wounds%20%3D%20this.actor.status.wounds%20if%20(wounds.value%20%3D%3D%200)%20%20%20%0D%0A%20%20%20%20return%20ui.notifications.error(%22No%20effect%20at%200%20Wounds%22)%20%20%0D%0A%0D%0Aui.notifications.notify(%60Healed%20$%7Bthis.actor.characteristics.t.bonus%7D%20Wounds%60)%20%0D%0Athis.actor.modifyWounds(this.actor.characteristics.t.bonus)&classification=Monospace)

### CODE REVIEW

**Comment by Forien** [comment]
I left some "artifact" code there, because I want to first see if you are okay with these changes. If yes, I will cleanup unused code/html :)

**Comment by moo-man** [comment]
How does this interact with the ACE Editor?

**Comment by Forien** [comment]
> How does this interact with the ACE Editor?

I think it doesn't. But can't confirm, because even when I am on `effect-refactor` branch, ACE editor is not visible to me at all.

So since I don't touch its styling at all (except making its parent to display things in column using flexbox), so it would still not be visible. 

I did try to give it some basic styling like `height`, `width` etc, but couldn't get it to work properly. And I'm not familiar with it at all to do anything more, but if you want I might give it another try.

**Comment by Forien** [comment]
Nevermind my previous comment, it turned out to be easy with the following call:
```js
this.editor.resize();
```
It now supports acelib.

gif

However, I cannot make it to highlight Javascript, which kinda defeats the purpose of the mod. I encountered this error:
image

**Comment by silentmark** [comment]
You can check my PR that addresses this and maybe include it ;) https://github.com/moo-man/WFRP4e-FoundryVTT/pull/1850/files/f85a7e8ebdad3cb09fbfd9afe3298d1d5c829d5c#r1439809818

**Comment by Forien** [comment]
> You can check my PR that addresses this and maybe include it ;) https://github.com/moo-man/WFRP4e-FoundryVTT/pull/1850/files/f85a7e8ebdad3cb09fbfd9afe3298d1d5c829d5c#r1439809818

I think fixing the Ace Editor related errors it's outside of scope of this PR which focused on styling only. Also if your PR gets merged, then it's better if I do not change anything there ;)

**Pull request merged**
