### PR TITLE
combat refactor

### PR DESCRIPTION
**Pull request by silentmark**
Some improvements in combat scripts. Better handling current combatant / previous combatant for turn change. This helps to avoid scripts execution when you move back and forth on combat tracker. I have also unified the way how effects and combat scripts are executed - always first execute scripts and then effects. This is useful as in fact, i started to add new scripts in my module to the list of combat scripts.

### CODE REVIEW

**Comment by moo-man** [comment]
`always first execute scripts and then effects`

I'm not sure I understand this, effects don't "execute" anymore, it's always their scripts. Is there an example of what you mean here?

**Comment by silentmark** [comment]
Look at ```checkDiseases``` method - it has ```await Promise.all(turn.actor.runScripts("endRound", combat, {async: true}))``` at the end - and this method is the last method of endRound scripts - so its executed at the end, but if for example you would add another script to this endRound list - it wouldn't be true anymore.

**Comment by moo-man** [comment]
The only thing changed about that method in this PR is that it has become async, it does not call any scripts. Am I looking in the wrong place?

**Comment by silentmark** [comment]
for this particular example, the async is made only for consistency with other methods. as for main change, the ```await Promise.all(turn.actor.runScripts("endRound", combat, {async: true}))``` has been moved to ```static async updateCombat(combat, changes, context)``` this way its more readable and in case of extension of ```CombatHelpers.scripts.endRound``` - it will remain consistent. First scripts, then effects.

**Comment by moo-man** [comment]
I will also point out that much of this is code that hasn't been refactored yet. Ideally conditions will be handled no differently than any other effect that has scripts, instead of referencing a separate script via condition key and specifically calling it.

**Comment by silentmark** [comment]
I hope in case of refactoring of this part, you could take into account some of my suggestions ;-)

**Comment by moo-man** [comment]
It simply depends on how easy it is to move condition scripts into effect scripts. This would result in removing `checkStartTurnConditions`, `checkEndTurnConditions`, and `checkEndRoundConditions` entirely, but otherwise there probably won't be conflicts.

**Comment by silentmark** [comment]
the main problem i see there is fact, that those effects would have to be present and duplicated on every actor, which may lead to number of problems i guess. From the other hand - this mechanism to inject into combat flow with custom scripts is quite useful, the main problem i had at the beginning was inconsistency on combatant change and multiple execution of effects when switching the combatant order.

**Comment by moo-man** [comment]
> those effects would have to be present and duplicated on every actor

The effects are already on every actor. If three different tokens have Ablaze, they all have an independent Ablaze effect, the difference is that the script is not within the effect, it is shared between them in config.

**Pull request merged**
