### PR TITLE
Added Spanish translation

### PR DESCRIPTION
**Pull request by Txus5012**
Hi.

Thanks again for your hard work. I wanted to contribute with a Spanish translation I made based in the Spanish Core Rulebook by Devir.

Almost everything in the lang file is translated, except for a few things that would break some automations if translated:

- Characteristics: The full names aren't translated. The abbrevs are, as far as I've tested they didn't break anything.
Bonuses aren't translated either.
- Skills, Talents and Traits.
- Conditions: They would work, but the links would show 'undefined'.
- Weapon Groups: Because they have to match the Skills.
- Money (GC, SS and CP).

Hit Locations are translated, the only issue is that the opposed test shows _Bodypart_ (Remapped). I think we can live with that.

Also, I made the 'Blessed By' label and the Scatter table slightly wider. Now spanish words fit and english users shouldn't notice it.

### CODE REVIEW

**Comment by moo-man** [comment]
Hi, thanks, but generally I recommend people create a separate module for translations, and I'm pretty sure one already exists for Spanish

**Comment by Txus5012** [comment]
I see. I'll try to learn a bit about how to make modules.
I haven't seen a Spanish translation.

**Comment by Txus5012** [comment]
Oops, I didn't know this would be updated. I'm very new to this.
How can I cancel this pull request?

**Comment by moo-man** [comment]
Just "close" at the bottom, which I'll do with this comment

You can see how the french translation is done here https://gitlab.com/LeRatierBretonnien/foundryvtt-wh4-lang-fr-fr

**Pull request closed without merging**
